### PR TITLE
Fix PHPStan fix

### PR DESCRIPTION
**Pull request by szepeviktor**
as `CURLOPT_RETURNTRANSFER` is true

### CODE REVIEW

**Comment by mnapoli** [comment]
It triggered a phpcs error now, I'm not sure if it's all worth it 🤔

**Comment by szepeviktor** [comment]
I see! `HardMode` is an anti-PHPStan ruleset :)

**Comment by szepeviktor** [comment]
... an assertion would consume CPU clock cycles

**Comment by mnapoli** [comment]
It's based on the Doctrine ruleset ^^

**Pull request closed without merging**
